Do not abort bufr reading if message has invalid date information
metno/pysurfex pull request #31
Opened 2023-09-26 14:24 UTC by trygveasp

2023-09-26 16:11 UTC, joewkr requested changes

2023-09-26 16:11 UTC, joewkr commented on pysurfex/bufr.py
> +        number_of_lines = int(len(lines_in_file))
Looks a bit strange to see `readlines` for a file opened in the binary mode. Why not using a combination of `seek` and `tell` to get the file size and then `tell` in the loop to derive the percentage of processed data?

2023-09-26 19:26 UTC, joewkr requested changes

2023-09-26 19:26 UTC, joewkr commented on pysurfex/bufr.py
> +                        logging.info("Read: %s%%", processed)
Do you really need a list there? Wouldn't it suffice to have something like:
```python
if processed > processed_threshold and processed % 5 == 0:
    processed_threshold = processed
    logging.info("Read: %s%%", processed)
```

2023-09-26 19:26 UTC, joewkr commented on pysurfex/bufr.py
> +        processed_threshold = [0]
See below

2023-09-27 09:05 UTC, trygveasp commented
Should be addressed now?

2023-09-27 09:22 UTC, joewkr approved these changes
LGTM

2023-09-27 09:22 UTC, merged