pySurfex EnKF
metno/pysurfex pull request #6
Opened 2022-05-10 12:31 UTC by josteinblyverket

Latest updates to allow for the EnKF in HARMONIE-AROME

2022-05-16 08:03 UTC, trygveasp commented
Why do you turn off snow observations? What about snow assimilation?

2022-11-30 13:23 UTC, josteinblyverket commented
Updated with metno/pysurfex master merge.

2022-12-02 08:36 UTC, trygveasp requested changes

2022-12-02 08:36 UTC, trygveasp commented on examples/cfg/config_exp_EnKF.toml
> +ISBA = "ENSRKF"                         # Assimilation method for ISBA soil: "NONE"|"OI"|"EKF"
You must change this

2022-12-02 08:36 UTC, trygveasp commented on examples/cfg/config_exp_EnKF.toml
> +NNCO = [1, 1, 0, 0, 0]                      # Active observation types
And change this

2023-06-19 19:48 UTC, closed without merging